### ISSUE TITLE
Example algorithm of splitting up a history request

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1140]
#### Expected Behavior
Demonstration of breaking up a history request for users.

#### Actual Behavior
No live history request demonstrations. 

#### Potential Solution
Add C# and Python examples of split up history requests warming up indicators. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
I am closing this issue since I think we have solved the problem on the engineer's side: requests don't take more than 10 minutes. @EmilioFreire , are you still experiencing it?

One way to tackle this problem might be using the `Train` method to add more time to complete the request. In Python, we can also use `History[Trade]` to avoid the conversion to pandas Dataframe too.
