### ISSUE TITLE
Update OperationalRatios examples in Fundamental Data documentation

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Documentation#121]
Currently all of the examples in the OperationsRatios section of the Fundamental Data documentation have a `OneMonth` suffix when default is actually `OneYear`, and the only valid attributes are `OneYear`, `ThreeYears`, and `FiveYears`.

**Comment by jaredbroad** [comment]
https://github.com/QuantConnect/Documentation/blob/master/07%20Data%20Library/03%20Fundamentals/03%20Reference%20Tables.php#L43

its hard coded at the moment; any general rule we can apply?

**Comment by DerekMelchin** [comment]
This is fixed with the new[ dataset market listing](https://www.quantconnect.com/datasets/morning-star-us-fundamentals)
![image](https://user-images.githubusercontent.com/38889814/154772790-fd5ece43-c55c-417f-95fa-adbcd663ca6f.png)
The values are now generated by the inspector, so it should be up to date with Lean code.
