### ISSUE TITLE
lean cli reference auto gen

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1465]
#### Expected Behavior

The lean cli reference pages are auto generated

#### Actual Behavior

The reference pages are manually generated

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/b7aeef00094ce54cc4da3a361b160af4405c89b8
The script moves the directories and seeds "Introduction" and "Options", since they can easily be inferred from LEAN CLI ReadMe, then we need to manually create the other H3.
If there is a mission option, it's added as a HTML comment at the bottom of the Options.html file.
