### ISSUE TITLE
Adds Section About Mutil-Index in History 

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1495]
#### Expected Behavior
Teach how to handle history requests that return a dataframe for Futures and Options. e.g.: 
```python
history.index = history.index.droplevel(0)
```

#### Actual Behavior
Only documented in Research.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Also teach how to swap the index levels so that the dataframe index is datetime on the left and then Symbol on the right.
It could come at the bottom of the Python version of [Analyze Results](https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/history-requests#06-Analyze-Results).

**Comment by DerekMelchin** [comment]
https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/history-requests#06-Analyze-Results
