### ISSUE TITLE
Creating Alternative Data Using Python CLRImports

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1554]
#### Expected Behavior

This code snippet
```
map_file_provider = LocalZipMapFileProvider()
map_file_provider.Initialize(DefaultDataProvider())
```
includes `from CLRImports import *`

The script should run in the `bin` folder where we compile the files

- If using python, delete the process.* files that aren't python. And rename process.sample.py to process.py
- If using python, delete the downloader.cs (ex: QuantConnectMarketRegimeDataDownloader.cs) file and change the program.cs to be
```
using System;

Console.WriteLine("This data processor uses the Python script process.py");
```

#### Actual Behavior

The code snippet doesn't work as-is

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Most of these topics have been addressed.
- If using python, delete the downloader.cs (ex: QuantConnectMarketRegimeDataDownloader.cs) file and change the program.cs to be

is already covered by 
> In the Lean.DataSource.<vendorNameDatasetName> / DataProcessing / Program.cs file, remove the statements of the Main method

The only step missing is:
- The script should run in the bin folder where we compile the files

It should be step 12, because after we create the script, we got to bin, copy the script and run:
```
cd bin\Debug\net6.0\
cp ..\..\..\process.py .
python process.py
```
